### ISSUE TITLE
Animals skinning/texture issue

### ISSUE THREAD

**Issue by Git-Forked** [Skandarella/Animal-World#1]
Animals are not being properly skinned, sometimes 1 or no textures appear, and the rest of the animal is shown as white.
![Error_Animal-World](https://user-images.githubusercontent.com/66106762/107937620-2b562780-6f52-11eb-8317-0dedc2857028.png)

**Comment by Git-Forked** [comment]
![Error_Animal-World_2](https://user-images.githubusercontent.com/66106762/107938094-d830a480-6f52-11eb-9707-088ed6ab5848.png)

**Comment by Skandarella** [comment]
A known bug from many animal mods if Shader is not activated. Activate the Shader in Minetest Menu and it should work.

**Comment by Git-Forked** [comment]
Can you provide or link to instructions for how to activate the shader? Thank you for your quick reply.

**Comment by Git-Forked** [comment]
I think I found it if you meant as client side settings.  Waiting to find another animal to see if the issue is now resolved.

**Comment by Skandarella** [comment]
okay :)

**Comment by Skandarella** [comment]
The path is: Graphics/In-Game/Shaders Enable

**Comment by Git-Forked** [comment]
Issue solved, thank you very much for your time in answering issues, and your time spent making wonderful mods.

**Comment by Skandarella** [comment]
Thank you! :)

**Comment by techmouse** [comment]
I'm having this exact issue except my shaders _are_ enabled.

![screenshot_20210906_225453](https://user-images.githubusercontent.com/4404140/132277701-f84fcc40-524a-48af-ac39-327c9384200d.png)

**Comment by Skandarella** [comment]
Are you using Minetest 5.4.1 released. (April 10th 2021 ) ?
