### ISSUE TITLE
Feeding of different grasses for mobs

### ISSUE THREAD

**Issue by CowboyLva** [Skandarella/Animal-World#10]
Whilst trying to add support for this mod in ebiomes(Extra Biomes) I stumbled upon an issue.

Mobs only eat default:grass

For example the yak

	follow = {
		"farming:wheat", "default:grass_1", "farming:barley",
		"farming:oat", "farming:rye", "farming:carrot", "farming:beans", "farming:lettuce"
	},

For mod compatibility It may be best to let mobs follow group:grass or group:normal_grass instead.

Snippet from minetest's default grass

	groups = {snappy = 3, flora = 1, attached_node = 1, grass = 1,
			normal_grass = 1, flammable = 1},

**Comment by Skandarella** [comment]
I have updated all grass eating animals in the newest version on ContentDB a few minutes ago. It should work now.

**Comment by CowboyLva** [comment]
Thank you.
