### ISSUE TITLE
Can't use cow milk to make cheese

### ISSUE THREAD

**Issue by davidflavigne** [Skandarella/Animal-World#12]
It seems that the provided bucket of milk can only be used with yak. Once the mod was installed I could not farm a bucket of milk to use with cheese and other animalworld recipe as there was no yak around. 
I could get a bucket of milk with a cow, but it is unusable for recipes.

**Comment by Skandarella** [comment]
Should be fixed now, try it out, thanks!

**Comment by davidflavigne** [comment]
great, thanks!
