### ISSUE TITLE
Hunger_ng support

### ISSUE THREAD

**Issue by daretmavi** [Skandarella/Animal-World#2]
Hi,

please add satiation levels to the food from animals to add support for hunger mod.
https://gitlab.com/4w/hunger_ng/-/blob/master/doc/README.API.md

Thanx

**Comment by Skandarella** [comment]
Hi, i dont know what to do exactly. If i add this to my code for testing, an error occurs: 

hunger_ng.add_hunger_data('animalworld:chicken_cooked', {
    satiates = 1.5,
    heals = 0,
    returns = 'animalworld:chicken_cooked',
    timeout = 4
})

the ERROR: 

ModError: Failed to load and run script from D:\minetest-5.3.0-win64\bin\..\mods\Animal-World-main\init.lua:
...-5.3.0-win64\bin\..\mods\Animal-World-main/blackbird.lua:160: attempt to index global 'hunger_ng' (a nil value)
stack traceback:
	...-5.3.0-win64\bin\..\mods\Animal-World-main/blackbird.lua:160: in main chunk
	[C]: in function 'dofile'
	...etest-5.3.0-win64\bin\..\mods\Animal-World-main\init.lua:32: in main chunk
Siehe debug.txt für Details.

**Comment by daretmavi** [comment]
Did you add hunger_ng to mod conf as dependecy?

**Comment by Skandarella** [comment]
optional dependency?

**Comment by Skandarella** [comment]
i added hunger_ng to depends.txt but it changed nothing, bug. Should i add this to mod.conf?

**Comment by daretmavi** [comment]
I woul say both should work, only depends.txt is to support older minetest 0.4x
May be something else is wrong.

**Comment by Skandarella** [comment]
But where has this:

hunger_ng.add_hunger_data('animalworld:chicken_cooked', {
satiates = 1.5,
heals = 0,
returns = 'animalworld:chicken_cooked',
timeout = 4
})

to be? If i put it in the .lua of the animal, the bug appears

**Comment by Skandarella** [comment]
Im using the hunger mod from base_gameplay_modpack and it doesent work with that (my mistake, thought they where the same). I have downloaded the latest hunger_ng version and it worked. But: Only if the mod (hunger_ng) is activated. I cannot make the mod as a dependency, if i will do then nobody without this mod can use the animals anymore. When the mod hunger_ng is not activated but the animals .lua file has hunger data in it, the bug appears (nil value)

**Comment by daretmavi** [comment]
You can make it optional (`optional_depends = hunger_ng` in mod.conf) and test it in your mode with:
`if minetest.get_modpath("hunger_ng") then`

**Comment by daretmavi** [comment]
Btw.
This are satiation levels from mobs:
```
mobs:cheese',              { satiates = 2.5 }
mobs:chicked_egg_fried',   { satiates = 2 }
mobs:chicken_cooked',      { satiates = 5 }
mobs:chicken_egg_fried',   { satiates = 2 }
mobs:chicken_raw',         { satiates = 2, heals = -2 }
mobs:honey',               { satiates = 2 }
mobs:meat',                { satiates = 5.5 }
mobs:meat_raw',            { satiates = 2.5, heals = -1 }
mobs:mutton_cooked',       { satiates = 6, heals = 1 }
mobs:mutton_raw',          { satiates = 2, heals = -1 }
mobs:pork_cooked',         { satiates = 4 }
mobs:pork_raw',            { satiates = 1 }
mobs:rabbit_cooked',       { satiates = 4.5 }
mobs:rabbit_raw',          { satiates = 2, heals = -1 }
mobs:rat_cooked',          { satiates = 1.5 }
```
Maybe you could make them similar.

And thanx for quick response and great fork :+1:

**Comment by Skandarella** [comment]
As soon as i add it as a depend optional or not, the error occurs when the mod (hunger_ng) is not activated: 

ModError: Failed to load and run script from D:\minetest-5.3.0-win64\bin\..\mods\Animal-World-main\init.lua:
...etest-5.3.0-win64\bin\..\mods\Animal-World-main\init.lua:8: attempt to index global 'mobs' (a nil value)
stack traceback:
	...etest-5.3.0-win64\bin\..\mods\Animal-World-main\init.lua:8: in main chunk
Siehe debug.txt für Details.

"if minetest.get_modpath("hunger_ng") then" sadly does not fix the problem.

I really would like to get this to work, but i found no example in your supported mods. I searched in Ethereal for example and the food objects not have hunger values. where are they to find? Also is your mod not listed as a dependency in Ethereal.

**Comment by daretmavi** [comment]
Hi,
I'm not very experience in lua programing, but if you push your changes in new devel branch, I would look at it.

I would say something like this should work.
```
if minetest.get_modpath("hunger_ng") then
    hunger_ng.add_hunger_data('animalworld:chicken_cooked', {
    satiates = 1.5,
    heals = 0,
    timeout = 4
    })
end
```
In `hunger_ng/interoperability/` are some mod supported as fallback (if no support from mod dev).
E.g. for farming, see https://gitlab.com/4w/hunger_ng/-/blob/master/interoperability/farming.lua

**Comment by daretmavi** [comment]
Here is some implementation from petz.
https://github.com/runsy/petz/blob/master/petz/misc/hunger.lua

But I would suggest to add it for every mob separately (in mob definition), because it is too easy to forget to update separate lua file when you add new mob.

**Comment by Skandarella** [comment]
Now it seems to work but another bug appeared, if the mod (hunger_ng) is activated. I get constantly error messages about missing images in German, but they exist and there is also no dummy image that where created like you can see in the picture:
![bugpic](https://user-images.githubusercontent.com/75903112/108623540-d88fda80-743f-11eb-9f5f-3342948640f2.png)

Perhaps you can add the values in your mod yourself? I can send you a list with the values to use for the items, also for the new items from my (not yet released) floatlands mod with prehistoric meats.

**Comment by daretmavi** [comment]
Did you registered the food first?

**Comment by Skandarella** [comment]
It seems that the mod hudbars is in conflict with your mod, if I deactivate it, the error messages about missing images are gone. Finally I created a separate .lua file in my mod folder named hunger.lua and I entered the following values:

if minetest.get_modpath("hunger_ng") ~= nil then
	hunger_ng.add_hunger_data('animalworld:chicken_egg_fried', {
		satiates = 2.0,
	})
	hunger_ng.add_hunger_data('animalworld:chicken_raw', {
		satiates = 1.0,
	})
	hunger_ng.add_hunger_data('animalworld:chicken_cooked', {
		satiates = 3.0,
	})
	hunger_ng.add_hunger_data('animalworld:pork_raw', {
		satiates = 1.0,
	})
	hunger_ng.add_hunger_data('animalworld:pork_cooked', {
		satiates = 4.0,
	})
	hunger_ng.add_hunger_data('animalworld:rawfish', {
		satiates = 1.0,
	})
	hunger_ng.add_hunger_data('animalworld:cookedfish', {
		satiates = 2.0,
	})
	hunger_ng.add_hunger_data('animalworld:rabbit_raw', {
		satiates = 1.0,
	})
	hunger_ng.add_hunger_data('animalworld:rabbit_cooked', {
		satiates = 3.0,
	})
	hunger_ng.add_hunger_data('animalworld:rat_cooked', {
		satiates = 2.0,
	})
	hunger_ng.add_hunger_data('animalworld:raw_athropod', {
		satiates = 1.0,
	})
	hunger_ng.add_hunger_data('animalworld:cooked_athropod', {
		satiates = 2.0,
	})
	hunger_ng.add_hunger_data('animalworld:rawmollusk', {
		satiates = 1.0,
	})
	hunger_ng.add_hunger_data('animalworld:cookedmollusk', {
		satiates = 2.0,
	})
	hunger_ng.add_hunger_data('animalworld:butter', {
		satiates = 1.0,
	})
	hunger_ng.add_hunger_data('animalworld:bucket_milk', {
		satiates = 1.0,
	})
	hunger_ng.add_hunger_data('animalworld:cheese', {
		satiates = 2.0,
	})
end

Now it seems to work. Is there something else I must do?

A cool mod, I am a great fan of survival games and this mod makes it harder to survive, I like it!

**Comment by daretmavi** [comment]
Super, I hope this will work.
It is accually not my mod, but I use it in my game.
I'm a fan of survival as well and I really like your animals. One of the
best mods.


Dňa ne 21. 2. 2021, 15:41 Skandarella <notifications@github.com> napísal(a):

**Comment by Skandarella** [comment]
Thank you! :) You can download the latest version of the mod now here from github and test if it works.

**Comment by daretmavi** [comment]
It works.
I found only `animalworld:egg` which has no satiation.
Thanx
