### ISSUE TITLE
Textures are mostly black

### ISSUE THREAD

**Issue by z0rti** [Skandarella/Animal-World#4]
The textures are not displayed correctly for some reason
All animals are partially black, when i turn shaders off they are white
Using latest minetest 5.5.0 from git

**Comment by Skandarella** [comment]
5.5.0 is not officially released, so I will not support it now. Official version is 5.4.1

5.4.1 works with shaders.

**Comment by z0rti** [comment]
On my Android 10 devices, there are no shaders available, so everything is white.
Is it fixable in the *.b3d files? I managed to open one in Blender, but don't know what to do...

**Comment by Skandarella** [comment]
Without shaders the models cannot be displayed correctly. 
Someone in the forums found a way, but this would require to animate all models completely new:

https://forum.minetest.net/viewtopic.php?p=390641#p390641

I posted in another topic, that I am not able to do textures with blender and animate with armature, so there is no way to display the models correctly without shaders.
Someone who is skilled with blender would have to convert all my mods.

I cannot fix this, sorry.

**Comment by z0rti** [comment]
OK Thanks for explaining.
Then i hope there is a shader fix for Android
